version: '3'

vars:
  VERSION: "v0.1.3"
  BINARY_NAME: mpc-vol

tasks:
  build:
    desc: "バージョン情報を埋め込んでビルドします"
    cmds:
      - go build -ldflags "-X main.Version={{.VERSION}}" -o {{.BINARY_NAME}}
    sources:
      - ./*.go
    generates:
      - "{{.BINARY_NAME}}"

  clean:
    desc: "clean"
    cmds:
      - rm {{.BINARY_NAME}}

  tag:
    desc: "タグ打ち"
    cmds:
      - git tag {{.VERSION}}

